name: Build and Deploy Package

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          pip install -r requirements.txt
      - name: Build and package
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@27b2c7123570a1df7cfa03ab07f16d6a73ed8a27
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
